settings:
    # General plugin settings. 
    general:
        # Whether to anonymously send some trivial data (version, max players, etc) to the MCStats servers.
        stats: true
    # Economy settings.
    economy:
        # The singular name of your currency.
        currency-name: coin
        # The plural name of your currencey.
        currency-name-plural: coins
        # The amount of money players recieve when they join for the first time. 
        # Set to 0 and they won't get any.
        default-balance: 100
    advanced:
        # Whether to register with Vault or not.
        # It is recommended that you don't change this.
        register-vault: true
    # DO NOT TOUCH THIS!!!
    # This is essential to the survival of your configuration settings!
    config-version: 1.1
            
    
        
    

    
